### PR TITLE
fix: potential fix for textfile path issues (#7)

### LINKED ISSUE #7: Critical: Unable to resolve ascii art textfile paths
If I run the example command from the readme:

`hellhub statistics --limit 10 --filters="planet:name:@contains:a"`

I get this error:

```
➜ ~ hellhub statistics --limit 10 --filters="planet:name:@contains:a"
ENOENT: No such file or directory
   errno: -2
 syscall: "open"
   path: "/Users/jeff/ascii/statistics.txt"

➜ ~
```

Is there some sort of initialization step I need to do?

### PR DESCRIPTION
**Pull request by jeffgca**
I'm trying to guess the installed directory of the package using process.argv, but I'm unsure if this will break once the cli is installed via bun on a system.

Fixes #7

### CODE REVIEW

**Comment by fabio-nettis** [comment]
@jeffgca Could we not be using something like `__dirname` instead? This looks a bit unstable. Something along the lines of:

```typescript
path.join(__dirname, "../ascii", `${name}.txt`);
```

You can check the build output [here](https://www.npmjs.com/package/@hellhub-collective/cli?activeTab=code).

**Review by jeffgca — COMMENTED** [review]
Updated with __dirname, which I completely forgot about.

**Comment by fabio-nettis** [comment]
@jeffgca Checks don't pass yet.

**Comment by jeffgca** [comment]
> @jeffgca Checks don't pass yet.

Oh yeah, fixed that. It takes a really long time for the checks to run, wish I could run them before committing?

**Comment by fabio-nettis** [comment]
LGTM.

**Pull request merged**
